const {AuditLogEvent}=require("discord.js");
const {processSecurityAction}=require("./detector");
const {inspectBotAction}=require("../botSecurity/behavior");
const {analyzeContext}=require("../ai/analyzer");
const {update}=require("../security/adaptiveLevel");
const {inspectEscalation}=require("./escalation");
const {inspectOverwriteChange}=require("./overwrites");
const {inspectMemberRoleChange}=require("./memberRoles");
const {notifyOwnerOfRemoval}=require("../failsafe/selfProtection");
const MAP=new Map([[AuditLogEvent.ChannelDelete,"channelDelete"],[AuditLogEvent.ChannelCreate,"channelCreate"],[AuditLogEvent.RoleDelete,"roleDelete"],[AuditLogEvent.RoleCreate,"roleCreate"],[AuditLogEvent.RoleUpdate,"roleUpdate"],[AuditLogEvent.MemberBanAdd,"ban"],[AuditLogEvent.MemberKick,"kick"],[AuditLogEvent.MemberPrune,"prune"],[AuditLogEvent.BotAdd,"botAdd"],[AuditLogEvent.MemberRoleUpdate,"memberRoleUpdate"],[AuditLogEvent.ChannelOverwriteCreate,"permissionOverwrite"],[AuditLogEvent.ChannelOverwriteUpdate,"permissionOverwrite"],[AuditLogEvent.ChannelOverwriteDelete,"permissionOverwrite"],[AuditLogEvent.WebhookCreate,"webhookCreate"],[AuditLogEvent.WebhookUpdate,"webhookCreate"],[AuditLogEvent.WebhookDelete,"webhookCreate"],[AuditLogEvent.IntegrationCreate,"integration"],[AuditLogEvent.IntegrationUpdate,"integration"],[AuditLogEvent.IntegrationDelete,"integration"]]);
function registerAntiNukeEvents(client){client.on("guildAuditLogEntryCreate",async(entry,guild)=>{try{if(entry.targetId===client.user.id&&(entry.action===AuditLogEvent.MemberKick||entry.action===AuditLogEvent.MemberBanAdd)){await notifyOwnerOfRemoval(guild,client,entry.executorId);return;}await inspectEscalation(entry,guild);await inspectOverwriteChange(entry,guild);await inspectMemberRoleChange(entry,guild);const type=MAP.get(entry.action);if(!type||type==="memberRoleUpdate")return;const member=await guild.members.fetch(entry.executorId).catch(()=>null);if(member?.user.bot){const botRisk=await inspectBotAction(guild,entry.executorId,type);const context=analyzeContext({massActions:botRisk.risk>=60,targetedSecurityBot:false});update(guild.id,Math.max(botRisk.risk,context.risk));}await processSecurityAction(guild,entry.executorId,type,entry.targetId);}catch(error){console.error("Anti-nuke event error:",error);}});}
module.exports={registerAntiNukeEvents};