const timelines=new Map(),fingerprints=new Map(),graphs=new Map(),decisions=new Map();
const MAX=100;
function bucket(map,id){if(!map.has(id))map.set(id,[]);return map.get(id);}
function add(map,id,item){const a=bucket(map,id);const v={...item,time:Date.now()};a.push(v);if(a.length>MAX)a.shift();return v;}
function timeline(guild,event){return add(timelines,guild.id,event);}
function fingerprint(guild,incident){const action=incident.action||incident.type||"unknown";const key=action+"|"+(incident.actor||"system");const list=bucket(fingerprints,guild.id);let fp=list.find(x=>x.key===key);if(!fp){fp={key,pattern:action,actor:incident.actor||"system",count:0,firstSeen:Date.now(),lastSeen:Date.now()};list.push(fp);}fp.count++;fp.lastSeen=Date.now();if(list.length>MAX)list.shift();return fp;}
function graph(guild,incident){const g=bucket(graphs,guild.id),edges=[];if(incident.actor)edges.push({from:"user:"+incident.actor,to:"action:"+(incident.action||incident.type||"security_event")});if(incident.action)edges.push({from:"action:"+incident.action,to:"incident:"+(incident.title||"security_event")});if(incident.targetId)edges.push({from:"action:"+(incident.action||incident.type||"security_event"),to:"target:"+incident.targetId});for(const e of edges)g.push({...e,time:Date.now()});while(g.length>MAX*3)g.shift();return edges;}
function decision(guild,incident,action){return add(decisions,guild.id,{title:incident.title||"Security decision",risk:incident.risk??"unknown",reason:incident.description||"Policy evaluation",action,authority:"LOCAL_SECURITY_POLICY"});}
function formatForLog(guild,incident,action){const t=timeline(guild,{event:incident.title||"Security event",action:incident.action||incident.type||"unknown",actor:incident.actor||null,evidence:incident.evidence||null});const fp=fingerprint(guild,incident),edges=graph(guild,incident),d=decision(guild,incident,action||"monitor");return [{name:"🕵️ Attack Timeline",value:"Event recorded at <t:"+Math.floor(t.time/1000)+":T> • "+t.event},{name:"🧬 Attack Fingerprint",value:fp.pattern+" • occurrences="+fp.count+" • actor="+fp.actor},{name:"🕸️ Attack Graph",value:edges.length?edges.map(e=>"`"+e.from+"` → `"+e.to+"`").join("\n").slice(0,1000):"No relationships recorded."},{name:"🧠 Explainable Decision",value:"Authority: "+d.authority+"\nReason: "+d.reason+"\nAction: "+d.action},{name:"💾 Recovery Snapshot",value:"Recovery baseline is tracked automatically."}];}
module.exports={timeline,fingerprint,graph,decision,formatForLog};