const fs=require("fs"),path=require("path");
const DATA_DIR=path.join(__dirname,"..","data"),CONFIG_FILE=path.join(DATA_DIR,"guilds.json");
const DEFAULT_CONFIG={security:{enabled:true,alertChannelId:null,trustedUserIds:[],trustedRoleIds:[],trustedBotIds:[],action:"strip_roles",cooldownSeconds:30},antinuke:{enabled:true,strictPermissions:true,strictOverwrites:true,strictMemberRoles:true,panicThreshold:3,windowSeconds:15,thresholds:{channelDelete:3,channelCreate:5,roleDelete:3,roleCreate:5,roleUpdate:5,ban:4,kick:4,webhookCreate:2,dangerousPermission:1,permissionOverwrite:2,integration:1,prune:1,botAdd:1}},antiraid:{enabled:true,joinThreshold:10,windowSeconds:20,raidModeMinutes:10,minimumAccountAgeDays:0,slowJoinWindowMinutes:30,slowJoinThreshold:25},joingate:{enabled:true,minimumAccountAgeMinutes:0,requireAvatar:false,inviteInProfile:false,containDangerousBots:true},automod:{enabled:true,heatThreshold:100,decayPerSecond:1,raidMentionThreshold:50,raidMentionWindowSeconds:30},backups:{enabled:true,intervalHours:3,keepVersions:10,ownerApprovalRestore:true},verification:{enabled:false,channelId:null,verifiedRoleId:null,unverifiedRoleId:null},logs:{security:null,raid:null,verification:null}};
function ensureStorage(){if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(CONFIG_FILE))fs.writeFileSync(CONFIG_FILE,"{}");}
const clone=v=>JSON.parse(JSON.stringify(v));function deepMerge(target,source){for(const k of Object.keys(source||{})){const v=source[k];if(v&&typeof v==="object"&&!Array.isArray(v)){if(!target[k]||typeof target[k]!=="object"||Array.isArray(target[k]))target[k]={};deepMerge(target[k],v);}else target[k]=v;}return target;}
function loadConfigs(){ensureStorage();try{const raw=fs.readFileSync(CONFIG_FILE,"utf8").trim();return raw?JSON.parse(raw):{};}catch(e){console.error("Failed to load guild configuration:",e);return{};}}
function saveConfigs(configs){ensureStorage();const tmp=CONFIG_FILE+".tmp";fs.writeFileSync(tmp,JSON.stringify(configs,null,2));fs.renameSync(tmp,CONFIG_FILE);}
function getGuildConfig(guildId){const configs=loadConfigs(),current=configs[guildId]||{},merged=deepMerge(clone(DEFAULT_CONFIG),current);if(JSON.stringify(current)!==JSON.stringify(merged)){configs[guildId]=merged;saveConfigs(configs);}return merged;}
function updateGuildConfig(guildId,updates){const configs=loadConfigs(),current=deepMerge(clone(DEFAULT_CONFIG),configs[guildId]||{});configs[guildId]=deepMerge(current,updates);saveConfigs(configs);return configs[guildId];}
function resetGuildConfig(guildId){const configs=loadConfigs();configs[guildId]=clone(DEFAULT_CONFIG);saveConfigs(configs);return configs[guildId];}
module.exports={DEFAULT_CONFIG,getGuildConfig,updateGuildConfig,resetGuildConfig};